name: "streampulse"
version: "1.0.0"

profile: "streampulse"

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  streampulse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table